

pub fn convert__knobs__from__0_1_0(from: &crate::victron_controller::dashboard::v0_1_0::knobs::Knobs) -> crate::victron_controller::dashboard::knobs::Knobs {
    crate::victron_controller::dashboard::knobs::Knobs {
        force_disable_export: from.force_disable_export.clone(),
        export_soc_threshold: from.export_soc_threshold.clone(),
        discharge_soc_target: from.discharge_soc_target.clone(),
        battery_soc_target: from.battery_soc_target.clone(),
        full_charge_discharge_soc_target: from.full_charge_discharge_soc_target.clone(),
        full_charge_export_soc_threshold: from.full_charge_export_soc_threshold.clone(),
        discharge_time: serde_json::from_value(serde_json::to_value(&from.discharge_time).unwrap()).unwrap(),
        debug_full_charge: serde_json::from_value(serde_json::to_value(&from.debug_full_charge).unwrap()).unwrap(),
        pessimism_multiplier_modifier: from.pessimism_multiplier_modifier.clone(),
        disable_night_grid_discharge: from.disable_night_grid_discharge.clone(),
        charge_car_boost: from.charge_car_boost.clone(),
        charge_car_extended: from.charge_car_extended.clone(),
        zappi_current_target: from.zappi_current_target.clone(),
        zappi_limit: from.zappi_limit.clone(),
        zappi_emergency_margin: from.zappi_emergency_margin.clone(),
        grid_export_limit_w: from.grid_export_limit_w.clone(),
        grid_import_limit_w: from.grid_import_limit_w.clone(),
        allow_battery_to_car: from.allow_battery_to_car.clone(),
        eddi_enable_soc: from.eddi_enable_soc.clone(),
        eddi_disable_soc: from.eddi_disable_soc.clone(),
        eddi_dwell_s: from.eddi_dwell_s.clone(),
        weathersoc_winter_temperature_threshold: from.weathersoc_winter_temperature_threshold.clone(),
        weathersoc_low_energy_threshold: from.weathersoc_low_energy_threshold.clone(),
        weathersoc_ok_energy_threshold: from.weathersoc_ok_energy_threshold.clone(),
        weathersoc_high_energy_threshold: from.weathersoc_high_energy_threshold.clone(),
        weathersoc_too_much_energy_threshold: from.weathersoc_too_much_energy_threshold.clone(),
        writes_enabled: from.writes_enabled.clone(),
        forecast_disagreement_strategy: serde_json::from_value(serde_json::to_value(&from.forecast_disagreement_strategy).unwrap()).unwrap(),
        charge_battery_extended_mode: serde_json::from_value(serde_json::to_value(&from.charge_battery_extended_mode).unwrap()).unwrap(),
    }
}